all: 2.2/1/set.c 2.2/2/swapInts.c 2.2/3/swapPtrs.c 2.2/4/singlyLinkedList.c 2.2/5/singlyLinkedList.c 2.2/6/singlyLinkedList.c 2.2/7/doublyLinkedList.c 2.2/9/BST.c 2.2/10/BST.c 2.3/1/bitcount.c 2.3/2/invert.c 2.3/3/rightRot.c 2.3/4/setBits.c
	gcc 2.2/1/set.c -o 2.2/1/a.out
	gcc 2.2/2/swapInts.c -o 2.2/2/a.out
	gcc 2.2/3/swapPtrs.c -o 2.2/3/a.out
	gcc 2.2/4/singlyLinkedList.c -o 2.2/4/a.out
	gcc 2.2/5/singlyLinkedList.c -o 2.2/5/a.out
	gcc 2.2/6/singlyLinkedList.c -o 2.2/6/a.out
	gcc 2.2/7/doublyLinkedList.c -o 2.2/7/a.out
	gcc 2.2/9/BST.c -o 2.2/9/a.out
	gcc 2.2/10/BST.c -o 2.2/10/a.out
	gcc 2.3/1/bitcount.c -o 2.3/1/a.out
	gcc 2.3/2/invert.c -o 2.3/2/a.out
	gcc 2.3/3/rightRot.c -o 2.3/3/a.out
	gcc 2.3/4/setBits.c -o 2.3/4/a.out
