all: 2.2/1/set.c 2.2/2/swapInts.c 2.2/3/swapPtrs.c 2.2/4/singlyLinkedList.c 2.2/5/singlyLinkedList.c 2.2/6/singlyLinkedList.c 2.2/7/doublyLinkedList.c 2.2/8/doublyLinkedList.c 2.2/9/BST.c 2.2/10/BST.c 2.3/1/bitcount.c 2.3/2/invert.c 2.3/3/rightRot.c 2.3/4/setBits.c
	gcc 2.2/1/set.c
	gcc 2.2/2/swapInts.c
	gcc 2.2/3/swapPtrs.c
	gcc 2.2/4/singlyLinkedList.c
	gcc 2.2/5/singlyLinkedList.c
	gcc 2.2/6/singlyLinkedList.c
	gcc 2.2/7/doublyLinkedList.c
	gcc 2.2/8/doublyLinkedList.c
	gcc 2.2/9/BST.c
	gcc 2.2/10/BST.c
	gcc 2.3/1/bitcount.c
	gcc 2.3/2/invert.c
	gcc 2.3/3/rightRot.c
	gcc 2.3/4/setBits.c
